export const imageTypes = {
  abstract: 'abstract',
  anime: 'anime',
  watercolor: 'watercolor',
  artNouveau: 'artNouveau',
  cartoon: 'cartoon',
  cyberpunk: 'cyberpunk',
  pixar: 'pixar',
  vanGogh: 'vanGogh',
  medievalFantasy: 'medievalFantasy',
  minimalist: 'minimalist',
  oil: 'oil',
  pixelArt: 'pixelArt',
  popArt: 'popArt',
  realistic: 'realistic',
  surrealist: 'surrealist',
};
