export const imageTypes = {
  abstract: 'abstract',
  anime: 'anime',
  watercolor: 'watercolor',
  'art-nouveau': 'artNouveau',
  cartoon: 'cartoon',
  cyberpunk: 'cyberpunk',
  pixar: 'pixar',
  'van-gogh': 'vanGogh',
  'medieval-fantasy': 'medievalFantasy',
  minimalist: 'minimalist',
  oil: 'oil',
  'pixel-art': 'pixelArt',
  'pop-art': 'popArt',
  realistic: 'realistic',
  surrealist: 'surrealist',
};
